[params]

title = "Carlos García Márquez"
author = "C. García Márquez"
description = "Software Engineer & DevOps"
customCss = ["css/custom.css"]
profilePicture = "images/profile.jpg"
disableTitleCapitalization = true
disableArchiveTitleStyling = true

singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Archive"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/carlosgarciamarquez/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/4kxz"

[[params.socialIcons]]
icon = "fab fa-itch-io"
title = "Itch.io"
url = "https://4kxz.itch.io/"
